apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: db
  namespace: default
spec:
  owner:
    projectName: notes
  componentType:
    name: deployment/service
    kind: ClusterComponentType
