apiVersion: openchoreo.dev/v1alpha1
kind: ReleaseBinding
metadata:
  name: shippingservice-development
  namespace: default
spec:
  environment: development
  owner:
    componentName: shippingservice
    projectName: online-boutique
  releaseName: shippingservice-20260514-1
