apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: emailservice
  namespace: default
spec:
  owner:
    projectName: online-boutique
  componentType:
    name: deployment/service
    kind: ClusterComponentType
