apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: api
  namespace: default
spec:
  owner:
    projectName: notes
  componentType:
    name: deployment/service
    kind: ClusterComponentType
  workflow:
    kind: ClusterWorkflow
    name: docker-gitops-release
    parameters:
      componentName: api
      projectName: notes
      repository:
        url: https://github.com/rashadism/notes-app
        revision:
          branch: main
          commit: 4d580bda0e7dc4f7ca9a3d3f03a6d2797e92388a
        appPath: /api
      docker:
        context: /api
        filePath: /api/Dockerfile
      workloadDescriptorPath: workload.yaml
  autoBuild: false
  autoDeploy: true
