apiVersion: openchoreo.dev/v1alpha1
kind: ClusterAuthzRole
metadata:
  annotations:
    meta.helm.sh/release-name: openchoreo-control-plane
    meta.helm.sh/release-namespace: openchoreo-control-plane
  labels:
    app.kubernetes.io/instance: openchoreo-control-plane
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: openchoreo-control-plane
    app.kubernetes.io/part-of: openchoreo
    app.kubernetes.io/version: latest-dev
    helm.sh/chart: openchoreo-control-plane-0.0.0-latest-dev
    openchoreo.io/bootstrap: "true"
  name: namespace-reader
spec:
  actions:
    - namespace:view
    - environment:view
    - deploymentpipeline:view
    - dataplane:view
    - workflowplane:view
    - observabilityplane:view
    - componenttype:view
    - resourcetype:view
    - trait:view
    - workflow:view
    - secretreference:view
