apiVersion: openchoreo.dev/v1alpha1
kind: ReleaseBinding
metadata:
  name: currencyservice-development
  namespace: default
spec:
  environment: development
  owner:
    componentName: currencyservice
    projectName: online-boutique
  releaseName: currencyservice-20260514-1
