apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: shippingservice
  namespace: default
spec:
  owner:
    componentName: shippingservice
    projectName: online-boutique
  container:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice:v0.10.5
    env:
      - key: PORT
        value: "50051"
      - key: DISABLE_PROFILER
        value: "1"
  endpoints:
    grpc:
      type: TCP
      port: 50051
