apiVersion: openchoreo.dev/v1alpha1
kind: ReleaseBinding
metadata:
  name: emailservice-development
  namespace: default
spec:
  environment: development
  owner:
    componentName: emailservice
    projectName: online-boutique
  releaseName: emailservice-20260514-1
