apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: productcatalogservice
  namespace: default
spec:
  owner:
    componentName: productcatalogservice
    projectName: online-boutique
  container:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice:v0.10.5
    env:
      - key: PORT
        value: "3550"
      - key: DISABLE_PROFILER
        value: "1"
  endpoints:
    grpc:
      type: TCP
      port: 3550
